version: '3.9'
services:
  # API DyPD container
  dyp:
    container_name: api-dypd
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      python manage.py collectstatic --no-input &&
      gunicorn --bind :8000 --workers 4 --threads 4 --timeout 30 configuracion.wsgi:application"
    
    #  gunicorn --bind :8000 --workers 4 --threads 4 --timeout 30 configuracion.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
    volumes:
      - ./staticfiles:/app/staticfiles
    networks:
      - app_network

  # Redis container
  redis:
    image: redis:6.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  # Celery container
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=info --pool=threads --concurrency=4
    image: celery
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
