# Generated by Django 3.1.3 on 2023-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0002_alter_customer_id_alter_paymentscustomer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="paymentscustomer",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
