# Generated by Django 3.1.3 on 2023-04-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_attempt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="login_attempts",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
