# Generated by Django 4.2 on 2023-05-12 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0002_auditmodel"),
        ("backoffice", "0002_auto_20230418_0145"),
    ]

    operations = []
