# Generated by Django 3.1.3 on 2023-05-17 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0002_auditmodel"),
        ("backoffice", "0002_auto_20230418_0145"),
    ]

    operations = []
