# Generated by Django 4.2 on 2023-05-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0003_merge_0002_auditmodel_0002_auto_20230418_0145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
