# Generated by Django 4.2.1 on 2023-05-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0004_alter_auditmodel_id_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location_date",
            field=models.DateTimeField(null=True),
        ),
    ]
