# Generated by Django 3.1.3 on 2023-06-20 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0003_merge_20230513_1318"),
        ("backoffice", "0003_merge_20230517_0901"),
        ("backoffice", "0006_usersecurecode"),
    ]

    operations = []
