# Generated by Django 3.1.3 on 2023-07-06 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0006_usersecurecode"),
        ("backoffice", "0003_merge_20230517_0901"),
        ("backoffice", "0003_merge_20230513_1318"),
    ]

    operations = []
