# Generated by Django 3.1.3 on 2023-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0007_merge_20230628_0839"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditmodel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usersecurecode",
            name="code",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="usersecurecode",
            name="expedition_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="usersecurecode",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usersecurecode",
            name="tries",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
