# Generated by Django 4.2.1 on 2023-07-26 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0007_merge_20230630_1808"),
        ("backoffice", "0008_auto_20230628_0839"),
    ]

    operations = []
