# Generated by Django 4.2.1 on 2023-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0009_merge_20230726_1139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usersecurecode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
