# Generated by Django 4.2.1 on 2023-07-26 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0007_merge_20230706_1205"),
        ("backoffice", "0010_alter_auditmodel_id_alter_user_id_and_more"),
    ]

    operations = []
