# Generated by Django 4.2.1 on 2023-07-26 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0007_merge_20230620_1459"),
        ("backoffice", "0011_merge_20230726_1147"),
    ]

    operations = []
