# Generated by Django 4.2.1 on 2023-08-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0012_merge_20230726_1155"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersecurecode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
