# Generated by Django 4.2.1 on 2023-08-15 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0013_user_open_fin_token"),
        ("backoffice", "0013_usersecurecode_is_active"),
    ]

    operations = []
