# Generated by Django 4.2.1 on 2024-05-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0014_merge_20230815_0927"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="open_fin_refresh",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="open_fin_refresh_exp",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="open_fin_token_exp",
            field=models.IntegerField(null=True),
        ),
    ]
