# Generated by Django 4.2.1 on 2024-07-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0015_user_open_fin_refresh_user_open_fin_refresh_exp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_new_user",
            field=models.BooleanField(default=True),
        ),
    ]
