# Generated by Django 4.2.1 on 2024-07-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0016_user_is_new_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
