# Generated by Django 4.2.1 on 2024-08-30 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0018_rolesgroups"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log2FA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_2fa", models.BooleanField(default=False)),
                ("temp_code", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "log_2fa",
            },
        ),
    ]
