# Generated by Django 4.2.1 on 2024-10-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0019_log2fa"),
    ]

    operations = [
        migrations.AddField(
            model_name="log2fa",
            name="failed_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
