# Generated by Django 4.2.1 on 2024-10-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0020_log2fa_failed_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="log2fa",
            name="questions_attempt",
            field=models.IntegerField(default=0),
        ),
    ]
